# Edit these values as you prefer and change the name of the file to playout.yml

# Radia Management node base URI (without trailing slash)
base_uri: http://scheduler.radiozero.pt

# Radia Management visit interval (in seconds) 
interval: 30

# Scheduler
scheduler: 
    adapter: soma
    location: localhost
    port: 12521
    password: 'hackme'

# Base folder for downloads
downloads_folder: '/mnt/sata/radia-source/archive'

# Maximum number of downloads at the same time
max_downloads: 3

# Supported services
services:
    - service: 'ftp://ftp.radiozero.pt'
      user: 'radiologo'
      password: 'radiomix'
