--- 
- "Matin\xC3\xA9"
- PIB
- "Puntz! [S\xC3\xA1bado]"
- Radioswap
- 4x3
- Marca Branca
- Estado da Arte
- The Wild Rover
- High Vibes Sound
- Radiologia
- Soul Time
- Boa Noite e Um Queijo
- Vidas Alternativas
- "M\xC3\xBAsica de Peso"
- "Conc\xC3\xADlio Dos Deuses"
- Director's Cut
- Puntz! [Xinobi + EgoVision]
- "Outra Esta\xC3\xA7\xC3\xA3o"
- Bandidos Desesperados
- "A Minha Almofada Tem R\xC3\xA1dio"
- O Dia Em Que A Terra Parou
- Carter Hotel
- "Ch\xC3\xA1 com Mel"
- AGaragem.com
- "Patag\xC3\xB3nia"
- Pretty In Pink
- Pronto-a-Ouvir
- "S\xC3\xA9timo Som"
- Puntz! [Prego no Prato]
- AtletOnews
- Osso De Rodes
- Break & Enter
- Gravidade Zero
- Coffee Breakz
- Electricfukkers
- "Esta\xC3\xA7\xC3\xA3o de Inverno"
- Ritualis Metallum Infernalium
- "TransMiss\xC3\xA3o Conspira"
- Terra Pura
- Contrabando
- Until
- Puntz! [M-PeX]
- Invisual
- Bside
- Connexion Bizarre
- Naquelas Tardes Sem Nada Para Fazer
- "M\xC3\xBAsica Livre"
- Brasil
- The Sound Of Space
- Insert Coin
- Lado B
- "Hora Obl\xC3\xADqua"
- Beat Oven
- Puntz! [Silas Francisco + Ricardo Matos]
- Puntz! [ADS presents Melodic Euphoria]
- "M\xC3\xA1 Fama"
- Registos Sonoros
- "A Arte A Uma S\xC3\xB3 Voz"
- "Teoria dos N\xC3\xBAmeros Aleat\xC3\xB3rios"
